rect1=int(input("enter the length1"))
b=int(input("enter the width1"))
rect2=int(input("enter the length2"))
d=int(input("enter the width2"))
rect3=int(input("enter the length3"))
f=int(input("enter the width3"))
rect4=int(input("enter the length4"))
h=int(input("enter the width4"))
i=("area of rect1:",rect1*b)
print(i)
j=("area of rect2:",rect2*d)
print(j)
k=("area of rect3:",rect3*f)
print(k)
l=("area of rect4:",rect4*h)
print(l)