rect1=int(input("enter the length1"))
b=int(input("enter the width1"))
rect2=int(input("enter the length2"))
d=int(input("enter the width2"))
rect3=int(input("enter the length3"))
f=int(input("enter the width3"))
rect4=int(input("enter the length4"))
h=int(input("enter the width4"))
i=(rect1*b)
print("area of rect1 is:",i)
j=(rect2*d)
print("area of rect2 is:",j)
k=(rect3*f)
print("area of rect3 is:",k)
l=(rect4*h)
print("area of rect4 is:",l)